name: Service Test S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  minio_s3:
    runs-on: ubuntu-latest

    # Setup minio server
    services:
      minio:
        image: wktk/minio-server
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "minioadmin"
          MINIO_SECRET_KEY: "minioadmin"

    steps:
      - uses: actions/checkout@v3
      - name: Setup test bucket
        env:
          AWS_ACCESS_KEY_ID: "minioadmin"
          AWS_SECRET_ACCESS_KEY: "minioadmin"
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set local http://127.0.0.1:9000/ minioadmin minioadmin
          ./mc mb local/test

      - name: Test
        shell: bash
        run: go test ./tests/...
        env:
          TEST_DEBUG: on
          DAL_S3_TEST: on
          DAL_S3_BUCKET: test
          DAL_S3_ENDPOINT: "http://127.0.0.1:9000"
          DAL_S3_ACCESS_KEY_ID: minioadmin
          DAL_S3_SECRET_ACCESS_KEY: minioadmin

  anonymous_minio_s3:
    runs-on: ubuntu-latest

    # Setup minio server
    services:
      minio:
        image: wktk/minio-server
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "minioadmin"
          MINIO_SECRET_KEY: "minioadmin"

    steps:
      - uses: actions/checkout@v3
      - name: Setup test bucket
        run: |
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set local http://127.0.0.1:9000/ minioadmin minioadmin
          ./mc mb local/test
          ./mc anonymous set public local/test
      - name: Test
        shell: bash
        run: go test ./tests/...
        env:
          TEST_DEBUG: on
          DAL_S3_TEST: on
          DAL_S3_BUCKET: test
          DAL_S3_ENDPOINT: "http://127.0.0.1:9000"